class WP
  public
  def initialize()
    @options = list()
    change(choose())
  end

  private
  def list()
    options = []

    # + the next command depends on your wallpaper folder
    # + this list.txt is generated by the wallpaper.sh script
    fp = open "list.txt", "r"

    while string = fp.gets
      options << string
    end

    return options
  end

  def choose()
    puts "# which one do you want?"
    i = 1

    @options.each do |option|
      puts "  #{i}. #{option}"
      i += 1
    end

    print 'answer: '
    answer = Integer(gets.chomp)

    exit if (answer == 0)

    if answer > @options.size
      gen = Random.new
      return @options[gen.rand(@options.size-1)+1]
    else
      return @options[answer-1]
    end
    
  end

  def change(string)
    # + here i am using feh as my wallpaper manager
    # + most managers just need a location to
    # set up the wallpaper
    system "feh --bg-fill #{string}"
  end

end

WP.new
